VDP 13 + VDP 14
Bazookastudios/Dikke-Ploaten pull request #5
Opened 2019-04-03 09:46 UTC by VictorVanhove

Albumpagina is nu verkrijgbaar als ook image slideshow when clicking on more images. De issues die ik nog heb zijn: die data prefetch snap nog steeds nie hoe da te implementeren, de constraints in albumpagina, deze werken enkel deftig om iPhone XR en zit daar mee te sukkelen en dan nog de delete functionality. Dat laatste heb ik nog steeds niet deftig kunnen bekijken.

2019-04-03 12:52 UTC, vrwim requested changes
De reden waarom je view zo lagt is omdat je de images synchroon ophaalt (via `Data(contentsOf: URL(string: album.cover)`). Dat kan je verbeteren door AlamofireImage te gebruiken. Let wel: tableviewcellen worden opnieuw gebruikt!

Ook heb ik gemerkt dat je de `updateUI` methode niet gebruikt vanuit je zoekscherm.

`addSnapshotListener` vervangen door `getDocuments`: 

```Swift
	static func docToAlbum(document: QueryDocumentSnapshot) -> Album {
		let album = try! Mapper<Album>().map(JSON: document.data())
		album.id = document.documentID
		return album
	}
```

2019-04-03 12:52 UTC, vrwim commented on Dikke Ploaten/Controller/SearchViewController.swift
> +			album.userID = (Auth.auth().currentUser?.uid)!
Denk eens na over wat je hier precies doet, wat doet `?.` en wat doet `!`?

2019-04-03 12:52 UTC, vrwim commented on Dikke Ploaten/Controller/LaunchViewController.swift
> +				// TODO: data prefetch, geen idee hoe hier data in te laden en door te sturen
Alles in je code graag in het Engels

2019-04-03 15:23 UTC, VictorVanhove commented
Heb al je changes aangepast, enige wat nog niet werkt is die delete, heb generateDictionary aan toegevoegd like you said, maar cell blijft nog staan. Waarschijnlijk nog iets vergeten.

2019-04-04 08:02 UTC, vrwim requested changes
Nog 1 nitpick en 1 issue

2019-04-04 08:02 UTC, vrwim commented on Dikke Ploaten/Controller/SearchViewController.swift
> +		Database.shared.getAlbumList() { (albums) in
Een tip: hier kan je de `()` weglaten, zoek maar eens op "trailing closure swift"

Hoef je niet aan te passen, is gewoon een tip voor de toekomst. Maakt mooiere code imo

2019-04-04 08:02 UTC, vrwim commented on Dikke Ploaten/Controller/SignupViewController.swift
> +		NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: UIResponder.keyboardWillShowNotification, object: nil)
Opgelet! Hier voeg je de observers toe in je "didAppear" (als het scherm zichtbaar wordt), maar haal je ze pas weg in "deinit" (als het object weggegooid wordt). Hier voor de signup denk ik niet dat dit voor problemen zal zorgen (aangezien die toch iedere keer opnieuw aangemaakt wordt), maar als je dat doet op een tab, en je gaat 5x naar die tab, dan heb je 5 observers zonder dat die verwijderd worden.

Zorgen dat je in de tegenovergestelde richting observers gaat verwijderen (viewdidload -> viewdidunload, viewwillappear -> viewdiddisappear, viewdidappear -> viewwilldisappear)

Graag nog aanpassen

2019-04-04 08:02 UTC, vrwim commented on Dikke Ploaten/Services/Database.swift
> +	func getUserWantlist(completionHandler: @escaping (_ updatedCollection: [Album]) -> ()) {		db.collection("userWantlist").limit(to: 1000).getDocuments { querySnapshot, error in
Graag op een volgend lijntje

2019-04-04 08:22 UTC, merged